[versions]
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "31"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-lifecycle = "2.9.4"
composeMultiplatform = "1.10.0-alpha02"
kotlin = "2.2.20"
koin = "4.1.1"
kable = "0.40.0"
logger = "2.7.1"
moko = "0.20.1"
ksp = "2.2.20-2.0.3"
koin-annotations = "2.1.0"
datastore ="1.1.7"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
logger = { module = "io.github.aakira:napier", version.ref = "logger" }
kable = { module = "com.juul.kable:kable-core", version.ref = "kable" }
moko-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko" }
moko-main = { module = "dev.icerock.moko:permissions", version.ref = "moko" }
moko-ble = { module = "dev.icerock.moko:permissions-bluetooth", version.ref = "moko" }
koin-annotations = {module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations"}
koin-ksp-compiler = {module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations"}
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
datastore = {module ="androidx.datastore:datastore", version.ref ="datastore"}
datastore-preferences = {module ="androidx.datastore:datastore-preferences", version.ref ="datastore"}


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinComposeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
